config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	resources :products do
		resources :reviews
	end

	  root 'products#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :name, :price, :details, :presence => true

	has_attached_file :avatar, styles: { medium: "300x300>", thumb: 
  "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: 
  /\Aimage\/.*\z/

  has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user, optional: true
  belongs_to :product, optional: true

  validates :content, :presence => true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_many :reviews

         def admin?
    		admin
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	before_action :only => [:new, :edit, :destroy] do
    redirect_to new_user_session_path unless current_user && current_user.admin
  end

	def index
		@products = Product.all
		render :index
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new(product_params)
		if @product.save
			redirect_to products_path
		else
			render :new
		end
	end

	def show
		@product = Product.find(params[:id])
		render :show
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])
		if @product.update(product_params)
			redirect_to products_path
		else
			render :edit
		end
	end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy
		redirect_to products_path
	end


	private 
	def product_params
		params.require(:product).permit(:name, :price, :details, :avatar)
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :set_review, only: [:show, :edit, :update, :destroy]

  def new
    @product = Product.find(params[:product_id])
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    @review.user = current_user
    if @review.save
      redirect_to product_path(@product)
    else
      render 'new'
    end
  end


  def destroy
    @review.destroy
    @product = Product.find(params[:product_id])

    redirect_to product_path(@product)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end


  private

  def review_params
    params.require(:review).permit(:product_id, :content, :user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Craftsy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container-fluid">
 <nav class="navbar navbar-inverse navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand"><%= link_to "Craftsy", root_path %></div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <% if user_signed_in? -%>
            <ul class="nav navbar-nav navbar-right">
              <% if current_user && current_user.admin %>
              <li><%= link_to 'Add new Product', new_product_path %></li>
              <%end%>
              <li><%= link_to 'Account', edit_user_registration_path %></li>
              <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
            </ul>
          <% else -%>
            <ul class="nav navbar-nav pull-right">
              <li><%= link_to 'Sign up', new_user_registration_path %></li>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
            </ul>
          <% end -%>
        </div>
      </div>
    </nav>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
     <%= yield %>
</div><!-- end container -->
   
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
<div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: "form-control" %>
  </div>
    <div class="form-group">
    <%= f.label :details %><br>
    <%= f.text_field :details, class: "form-control" %>
  </div>
    <div class="form-group">
    <%= f.file_field :avatar %>
  </div>
  <br>
  <br>
  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-lg btn-primary" %>
  </div>

<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
  <% @products.each do |product| %>
  <div class="col-sm-6">
    <div class="card" style="width: 20rem;">
      <%= image_tag product.avatar.url(:medium) %>
      <div class="card-block">
        <h4 class="card-title"><%= product.name %></h4>
        <p class="card-text">$ <%= product.price %></p>
        <div class="btn btn-info"><%= link_to "View", product_path(product) %></div>
      </div>
    </div>
  </div>
  
  <% end %>

app/views/products/new.html.erb
<h2>New product</h2>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="card" style="width: 20rem;">
  <%= image_tag @product.avatar.url(:medium) %>
  <div class="card-block">
    <h4 class="card-title">
      <h4 class="card-title"><%= @product.name %></h4>
      <p class="card-text">$ <%= @product.price %></p></h4>
    <p class="card-text"><%= @product.details %></p>
    <a href="#" class="btn btn-primary">Add to cart</a>
  </div>
</div>

<% if current_user && current_user.admin %>

<div class="btn-group">
    <%= link_to 'Edit', edit_product_path(@product), class: "btn btn-default" %>
    <%= link_to 'Destroy', @product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
  </div>

  <% end %>


<h3 class="reviews_title">
  <%= @product.reviews.count %> reviews
</h3>

<div id="reviews">
  <%= render :partial => @product.reviews %>
</div>
<%= simple_form_for [@product, Review.new]  do |f| %>
  <div class="field">
    <%= f.text_area :content, class: "form-control" %>
  </div>
  <br>
  <%= f.submit "Add reviews", class: "btn btn-primary" %>
<% end %>

app/views/reviews/_form.html.erb
<%= form_with(model: review, local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.number_field :product_id, id: :review_product_id %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :review_content %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :review_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<div class="review">
	<div class="review-rating" data-score="<%= review.rating %>"></div>
	<p class="review-comment"><%= review.content %></p>

	<% if user_signed_in? %>
			<div class="links btn-group">
				<% if current_user && current_user.admin %>
					<%= link_to "Delete", product_review_path(review.product, review), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>
				<% end %>
			</div>
	<% end %>
</div>

app/views/reviews/edit.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="edit-review-form">
    <h1>Edit Review</h1>
    <%= simple_form_for ([@product, @review]) do |f| %>
      <div id="rating-form">
        <label>Rating</label>
      </div>
      <%= f.input :comment %>
      <%= f.button :submit, class: "btn-custom2" %>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="new-review-form">
    <h1> Post Review </h1>
    <%= render 'form' %>
  </div>
</div>